name: Release Brexx/370

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'V*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    name: Creating Brexx/370 release on tk5
    runs-on: [ubuntu-latest]
    container: mainframed767/brexx
    steps:
    - name: Run tk5
      working-directory: /
      run: /run.sh /mvs-tk5/
      
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Move Brexx
      run: |
        mkdir -p /brexx370/          
        mv * /brexx370/
      shell: bash
  
    - name: Wait for tk5
      working-directory: /
      run: /home/hercules/loaded.sh
      shell: bash
        
    - name: Build Release
      working-directory: /brexx370/
      env:
        WINEPREFIX: /tmp/
      run: make SYSTEM=TK5 && make SYSTEM=TK5 install && make SYSTEM=TK5 test && make SYSTEM=TK5 release
      shell: bash

    - name: Github Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{  github.ref_name }}
        prerelease: false
        body_path: /brexx370/build/README.txt
        generate_release_notes: true
        files: |
          /brexx370/build/BREXX.*.ZIP
