
name: Testing TK4-, TK5, MVS/CE

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master    
jobs:
  tk4-test:
    name: Testing tk4-
    runs-on: [ubuntu-latest]
    container: mainframed767/brexx

    steps:
    - name: Run tk4-
      working-directory: /
      run: /run.sh /tk4-/
      
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Move Brexx
      run: |
        mkdir -p /brexx370/          
        mv * /brexx370/
      shell: bash
  
    - name: Wait for tk4-
      working-directory: /
      run: /home/hercules/loaded.sh
      shell: bash

    - name: Test
      working-directory: /brexx370/
      env:
        WINEPREFIX: /tmp/
      run: make SYSTEM=TK4- && make SYSTEM=TK4- install && make SYSTEM=TK4- test
      shell: bash

  mvsce-test:
    name: Testing MVS/CE
    runs-on: [ubuntu-latest]
    container: mainframed767/brexx

    steps:
      
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Move Brexx
      run: |
        mkdir -p /brexx370/          
        mv * /brexx370/
      shell: bash

    - name: Test
      working-directory: /brexx370/
      env:
        WINEPREFIX: /tmp/
      run: make SYSTEM=MVSCE && make SYSTEM=MVSCE install && make SYSTEM=MVSCE test
      shell: bash

  tk5-test:
    name: Testing tk5
    runs-on: [ubuntu-latest]
    container: mainframed767/brexx

    steps:
    - name: Run tk5
      working-directory: /
      run: /run.sh /mvs-tk5/
      
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Move Brexx
      run: |
        mkdir -p /brexx370/          
        mv * /brexx370/
      shell: bash
  
    - name: Wait for tk5
      working-directory: /
      run: /home/hercules/loaded.sh
      shell: bash
      
    - name: Test
      working-directory: /brexx370/
      env:
        WINEPREFIX: /tmp/
      run: make SYSTEM=TK5 && make SYSTEM=TK5 install && make SYSTEM=TK5 test
      shell: bash
      
  pre-release:
    name: Brexx/370 Pre-release
    runs-on: [ubuntu-latest]
    needs: [mvsce-test, tk4-test, tk5-test]
    container: mainframed767/brexx

    steps:
    - name: Run tk5
      working-directory: /
      run: /run.sh /mvs-tk5/
      
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Move Brexx
      run: |
        mkdir -p /brexx370/          
        mv * /brexx370/
      shell: bash
  
    - name: Wait for tk5
      working-directory: /
      run: /home/hercules/loaded.sh
      shell: bash
      
    - name: Release
      working-directory: /brexx370/
      env:
        WINEPREFIX: /tmp/
      run: make SYSTEM=TK5 && make SYSTEM=TK5 release
      shell: bash

    - name: Github Pre-release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "Pre-release"
        prerelease: true
        body_path: /brexx370/build/README.txt
        generate_release_notes: true
        files: |
          /brexx370/build/BREXX.*.ZIP