
name: Test Brexx/370 in MVS/CE, TK5, and TK4-

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master    
jobs:
  tk4-test:
    name: Testing Brexx/370 on tk4-
    runs-on: [ubuntu-latest]
    container: mainframed767/brexx

    steps:
    - name: Run tk4-
      working-directory: /
      run: /run.sh /tk4-/
      
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Move Brexx
      run: |
        mkdir -p /brexx370/          
        mv * /brexx370/
      shell: bash
  
    - name: Wait for tk4-
      working-directory: /
      run: /home/hercules/loaded.sh
      shell: bash

    - name: Test
      working-directory: /brexx370/
      env:
        WINEPREFIX: /tmp/
      run: make SYSTEM=TK4- && make SYSTEM=TK4- install && make SYSTEM=TK4- test
      shell: bash

  tk5-test:
    name: Testing Brexx/370 on tk5
    runs-on: [ubuntu-latest]
    container: mainframed767/brexx

    steps:
    - name: Run tk4-
      working-directory: /
      run: /run.sh /mvs-tk5/
      
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Move Brexx
      run: |
        mkdir -p /brexx370/          
        mv * /brexx370/
      shell: bash
  
    - name: Wait for tk5
      working-directory: /
      run: /home/hercules/loaded.sh
      shell: bash
      
    - name: Test
      working-directory: /brexx370/
      env:
        WINEPREFIX: /tmp/
      run: make SYSTEM=TK5 && make SYSTEM=TK5 test
      shell: bash

  mvsce-test:
    name: Testing Brexx/370 on MVS/CE
    runs-on: [ubuntu-latest]
    container: mainframed767/brexx

    steps:
      
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Move Brexx
      run: |
        mkdir -p /brexx370/          
        mv * /brexx370/
      shell: bash

    - name: Test
      working-directory: /brexx370/
      env:
        WINEPREFIX: /tmp/
      run: make SYSTEM=MVSCE && make SYSTEM=MVSCE test
      shell: bash
